import { DndContext, DragEndEvent, PointerSensor, useDraggable, useDroppable, useSensor, useSensors } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CalendarPlus, Check, ChevronLeft, ChevronRight, Circle, History, Lock, LockOpen, RotateCcw, Sparkles, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { blockedPeriodsApi, eventsApi, scheduleApi } from "../api/resources";
import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { Card } from "../components/ui/Card";
import { Dialog } from "../components/ui/Dialog";
import { Field, Input, Select } from "../components/ui/Field";
import { useToast } from "../providers/ToastProvider";
import type { BlockedPeriod, DayOfWeek, EventCategory, EventOccurrence, ProposedBlock, ScheduleBlock, SchedulePreview, ScheduleVersion } from "../types/domain";

const days: DayOfWeek[] = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"];
const hours = Array.from({ length: 18 }, (_, index) => index + 6);
const blockSchema = z.object({ title: z.string().min(2), category: z.enum(["LECTURE", "WORK", "BUSINESS", "GYM", "TRAVEL", "REST", "PERSONAL", "MEETING", "OTHER"]), date: z.string().min(10), startTime: z.string(), endTime: z.string() }).refine((value) => value.startTime < value.endTime, { path: ["endTime"], message: "End must be after start" });
type BlockForm = z.infer<typeof blockSchema>;

function currentMonday() { const now = new Date(); const offset = now.getDay() === 0 ? -6 : 1 - now.getDay(); now.setDate(now.getDate() + offset); return localDate(now); }
function localDate(value: Date) { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; }
function shiftDate(date: string, daysToAdd: number) { const value = new Date(`${date}T00:00:00`); value.setDate(value.getDate() + daysToAdd); return localDate(value); }
function toMinutes(time: string) { const [hour, minute] = time.split(":").map(Number); return hour * 60 + minute; }
function toTime(minutes: number) { return `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`; }
function duration(start: string, end: string) { return (end === "00:00" ? 1440 : toMinutes(end)) - toMinutes(start); }
function formatMinutes(minutes: number) { return `${Math.floor(minutes / 60)}h${minutes % 60 ? ` ${minutes % 60}m` : ""}`; }

const sourceStyle = {
  MANUAL: "border-amber-400 bg-amber-100 text-amber-950 dark:border-amber-700 dark:bg-amber-950 dark:text-amber-100",
  GOAL: "border-teal-400 bg-teal-100 text-teal-950 dark:border-teal-700 dark:bg-teal-950 dark:text-teal-100",
  SUBJECT: "border-sky-400 bg-sky-100 text-sky-950 dark:border-sky-700 dark:bg-sky-950 dark:text-sky-100",
  SYSTEM: "border-violet-400 bg-violet-100 text-violet-950 dark:border-violet-700 dark:bg-violet-950 dark:text-violet-100",
  EVENT: "border-slate-400 bg-slate-100 text-slate-950 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-100"
};

export function WeekPage() {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const [weekStart, setWeekStart] = useState(currentMonday);
  const [mobileDay, setMobileDay] = useState<DayOfWeek>(days[Math.max(0, (new Date().getDay() || 7) - 1)]);
  const [preview, setPreview] = useState<SchedulePreview | null>(null);
  const [selectedEvent, setSelectedEvent] = useState<EventOccurrence | null>(null);
  const [selectedBlock, setSelectedBlock] = useState<ScheduleBlock | null>(null);
  const [manualOpen, setManualOpen] = useState(false);
  const [undoVersionId, setUndoVersionId] = useState<string | null>(null);
  const [comparison, setComparison] = useState<ScheduleVersion | null>(null);
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }));
  const occurrences = useQuery({ queryKey: ["event-occurrences", weekStart], queryFn: () => eventsApi.occurrences(weekStart) });
  const blocks = useQuery({ queryKey: ["schedule-week", weekStart], queryFn: () => scheduleApi.week(weekStart) });
  const periods = useQuery({ queryKey: ["blocked-periods", weekStart], queryFn: () => blockedPeriodsApi.list(weekStart) });
  const versions = useQuery({ queryKey: ["schedule-versions", weekStart], queryFn: () => scheduleApi.versions(weekStart) });
  const form = useForm<BlockForm>({ resolver: zodResolver(blockSchema), defaultValues: { title: "", category: "WORK", date: weekStart, startTime: "09:00", endTime: "10:00" } });
  const dates = useMemo(() => Object.fromEntries(days.map((day, index) => [day, shiftDate(weekStart, index)])) as Record<DayOfWeek, string>, [weekStart]);
  const refresh = () => { void queryClient.invalidateQueries({ queryKey: ["schedule-week", weekStart] }); void queryClient.invalidateQueries({ queryKey: ["schedule-versions", weekStart] }); void queryClient.invalidateQueries({ queryKey: ["dashboard"] }); void queryClient.invalidateQueries({ queryKey: ["availability", weekStart] }); };

  const generate = useMutation({ mutationFn: () => scheduleApi.preview(weekStart), onSuccess: setPreview, onError: (error) => toast(error.message, "error") });
  const commit = useMutation({ mutationFn: (proposal: ProposedBlock[]) => scheduleApi.commit(weekStart, proposal), onSuccess: (result) => { setPreview(null); setUndoVersionId(result.previousVersionId); refresh(); toast(result.previousVersionId ? "Schedule updated. Undo is available." : "Schedule updated. There is no earlier version to restore."); }, onError: (error) => toast(error.message, "error") });
  const create = useMutation({ mutationFn: scheduleApi.createBlock, onSuccess: () => { setManualOpen(false); form.reset({ title: "", category: "WORK", date: weekStart, startTime: "09:00", endTime: "10:00" }); refresh(); toast("Manual block added"); }, onError: (error) => toast(error.message, "error") });
  const lock = useMutation({ mutationFn: ({ id, locked }: { id: string; locked: boolean }) => scheduleApi.lockBlock(id, locked), onSuccess: (block) => { setSelectedBlock(block); refresh(); toast(block.locked ? "Block locked" : "Block unlocked"); }, onError: (error) => toast(error.message, "error") });
  const complete = useMutation({ mutationFn: ({ id, completed }: { id: string; completed: boolean }) => scheduleApi.completeBlock(id, completed), onSuccess: (block) => { setSelectedBlock(block); refresh(); toast(block.completed ? "Marked complete" : "Marked incomplete"); }, onError: (error) => toast(error.message, "error") });
  const remove = useMutation({ mutationFn: scheduleApi.deleteBlock, onSuccess: () => { setSelectedBlock(null); refresh(); toast("Block deleted"); }, onError: (error) => toast(error.message, "error") });
  const restore = useMutation({ mutationFn: scheduleApi.restoreVersion, onSuccess: (result) => { setUndoVersionId(result.previousVersionId); refresh(); toast("Schedule version restored"); }, onError: (error) => toast(error.message, "error") });
  const compare = useMutation({ mutationFn: scheduleApi.version, onSuccess: setComparison, onError: (error) => toast(error.message, "error") });
  const move = useMutation({
    mutationFn: async (payload: { blockId: string; newDate: string; newStartTime: string; newEndTime: string }) => { await scheduleApi.validateMove(payload); return scheduleApi.updateBlock(payload.blockId, { date: payload.newDate, startTime: payload.newStartTime, endTime: payload.newEndTime }); },
    onSuccess: () => { refresh(); toast("Block moved"); }, onError: (error) => toast(error.message, "error")
  });

  const onDragEnd = (event: DragEndEvent) => {
    const block = (blocks.data ?? []).find((item) => item.id === event.active.id);
    const target = String(event.over?.id ?? "");
    if (!block || !target.includes("|")) return;
    const [newDate, hourText] = target.split("|");
    const newStartTime = `${hourText.padStart(2, "0")}:00`;
    move.mutate({ blockId: block.id, newDate, newStartTime, newEndTime: toTime(toMinutes(newStartTime) + duration(block.startTime, block.endTime)) });
  };
  const changeWeek = (amount: number) => { setWeekStart((current) => shiftDate(current, amount)); setPreview(null); setUndoVersionId(null); };

  return <DndContext sensors={sensors} onDragEnd={onDragEnd}>
    <div className="grid gap-6">
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 className="text-3xl font-semibold">My Week</h1><p className="mt-2 text-muted-foreground">Drag unlocked work to an hourly slot. Every move is validated before it is saved.</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => { form.setValue("date", weekStart); setManualOpen(true); }}><CalendarPlus className="size-4" /> Manual block</Button><Button onClick={() => generate.mutate()} disabled={generate.isPending}><Sparkles className="size-4" />{generate.isPending ? "Generating..." : "Generate schedule"}</Button></div></div>
      {undoVersionId ? <div className="flex items-center justify-between rounded-md border border-teal-300 bg-teal-50 p-3 text-sm text-teal-950 dark:border-teal-800 dark:bg-teal-950 dark:text-teal-100"><span>Schedule updated successfully.</span><Button variant="secondary" onClick={() => restore.mutate(undoVersionId)} disabled={restore.isPending}><RotateCcw className="size-4" /> Undo</Button></div> : null}
      <div className="flex items-center justify-between border-y border-border py-3"><Button variant="ghost" onClick={() => changeWeek(-7)} aria-label="Previous week"><ChevronLeft className="size-4" /></Button><div className="text-center"><p className="font-medium">Week of {weekStart}</p><button className="mt-1 text-xs text-primary" onClick={() => setWeekStart(currentMonday())}>Today</button></div><Button variant="ghost" onClick={() => changeWeek(7)} aria-label="Next week"><ChevronRight className="size-4" /></Button></div>

      <div className="hidden overflow-auto rounded-md border border-border lg:block"><DesktopCalendar dates={dates} events={occurrences.data ?? []} blocks={blocks.data ?? []} periods={periods.data ?? []} onEvent={setSelectedEvent} onBlock={setSelectedBlock} /></div>
      <div className="lg:hidden"><div className="flex gap-1 overflow-x-auto border-b border-border pb-2">{days.map((day) => <button key={day} onClick={() => setMobileDay(day)} className={`min-w-14 rounded-md px-2 py-2 text-xs font-medium ${mobileDay === day ? "bg-primary text-primary-foreground" : "bg-muted"}`}>{day.slice(0, 3)}</button>)}</div><MobileDay date={dates[mobileDay]} events={(occurrences.data ?? []).filter((event) => event.dayOfWeek === mobileDay)} blocks={(blocks.data ?? []).filter((block) => block.date.slice(0, 10) === dates[mobileDay])} periods={(periods.data ?? []).filter((period) => period.date.slice(0, 10) === dates[mobileDay])} onEvent={setSelectedEvent} onBlock={setSelectedBlock} /></div>

      <Card><div className="flex items-center gap-2"><History className="size-4" /><h2 className="font-semibold">Schedule history</h2></div><div className="mt-3 grid gap-2">{versions.data?.length ? versions.data.map((version) => <div key={version.id} className="flex items-center justify-between gap-3 rounded-md border border-border p-3 text-sm"><div><span className="font-medium">{version.label ?? "Schedule version"}</span><p className="text-xs text-muted-foreground">{new Date(version.createdAt).toLocaleString()} · {version.source} · {version._count?.blocks ?? 0} blocks</p></div><div className="flex gap-2"><Button variant="ghost" onClick={() => compare.mutate(version.id)}>Compare</Button>{version.active ? <Badge>ACTIVE</Badge> : <Button variant="secondary" onClick={() => restore.mutate(version.id)}>Restore</Button>}</div></div>) : <p className="text-sm text-muted-foreground">Commit a generated schedule to create version history.</p>}</div></Card>

      <Dialog open={Boolean(preview)} title="Schedule preview" description="Nothing is saved until you accept this proposal." onClose={() => setPreview(null)} wide>{preview ? <PreviewContent preview={preview} weekStart={weekStart} onCancel={() => setPreview(null)} onAccept={() => commit.mutate(preview.proposedBlocks)} accepting={commit.isPending} /> : null}</Dialog>
      <Dialog open={manualOpen} title="Add manual block" description="Manual blocks remain fixed during generation." onClose={() => setManualOpen(false)}><form className="grid gap-4" onSubmit={form.handleSubmit((data) => create.mutate(data))}><Field label="Title"><Input {...form.register("title")} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Category"><Select {...form.register("category")}>{(["LECTURE", "WORK", "BUSINESS", "GYM", "TRAVEL", "REST", "PERSONAL", "MEETING", "OTHER"] as EventCategory[]).map((category) => <option key={category}>{category}</option>)}</Select></Field><Field label="Date"><Input type="date" min={weekStart} max={shiftDate(weekStart, 6)} {...form.register("date")} /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Start"><Input type="time" {...form.register("startTime")} /></Field><Field label="End" error={form.formState.errors.endTime?.message}><Input type="time" {...form.register("endTime")} /></Field></div><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setManualOpen(false)}>Cancel</Button><Button disabled={create.isPending}>Add block</Button></div></form></Dialog>
      <Dialog open={Boolean(selectedEvent)} title={selectedEvent?.title ?? "Event details"} onClose={() => setSelectedEvent(null)}>{selectedEvent ? <div className="grid gap-3 text-sm"><p>{selectedEvent.date}, {selectedEvent.startTime}-{selectedEvent.endTime}</p><Badge>{selectedEvent.overridden ? "OVERRIDDEN" : "FIXED"}</Badge></div> : null}</Dialog>
      <Dialog open={Boolean(selectedBlock)} title={selectedBlock?.title ?? "Block details"} onClose={() => setSelectedBlock(null)}>{selectedBlock ? <div className="grid gap-4"><div className="flex gap-2"><Badge>{selectedBlock.sourceType}</Badge>{selectedBlock.locked ? <Badge>LOCKED</Badge> : null}{selectedBlock.completed ? <Badge>COMPLETE</Badge> : null}</div><p className="text-sm">{selectedBlock.date.slice(0, 10)}, {selectedBlock.startTime}-{selectedBlock.endTime} · {formatMinutes(duration(selectedBlock.startTime, selectedBlock.endTime))}</p><div className="flex flex-wrap justify-between gap-2"><div className="flex gap-2"><Button variant="secondary" onClick={() => complete.mutate({ id: selectedBlock.id, completed: !selectedBlock.completed })}>{selectedBlock.completed ? <Circle className="size-4" /> : <Check className="size-4" />}{selectedBlock.completed ? "Mark incomplete" : "Mark complete"}</Button><Button variant="secondary" onClick={() => lock.mutate({ id: selectedBlock.id, locked: !selectedBlock.locked })}>{selectedBlock.locked ? <LockOpen className="size-4" /> : <Lock className="size-4" />}{selectedBlock.locked ? "Unlock" : "Lock"}</Button></div><Button variant="danger" onClick={() => window.confirm("Delete this schedule block?") && remove.mutate(selectedBlock.id)}><Trash2 className="size-4" /> Delete</Button></div></div> : null}</Dialog>
      <Dialog open={Boolean(comparison)} title="Version comparison" description="Changes from this snapshot to the active schedule." onClose={() => setComparison(null)}>{comparison?.comparison ? <div className="grid gap-4 text-sm"><ComparisonGroup title="Added in current" blocks={comparison.comparison.added} /><ComparisonGroup title="Removed from current" blocks={comparison.comparison.removed} /><div><h3 className="font-medium">Moved or resized</h3><p className="mt-1 text-muted-foreground">{comparison.comparison.changed.length} changed blocks</p></div></div> : null}</Dialog>
    </div>
  </DndContext>;
}

function ComparisonGroup({ title, blocks }: { title: string; blocks: ScheduleBlock[] }) { return <div><h3 className="font-medium">{title}</h3>{blocks.length ? blocks.map((block) => <p key={block.id} className="mt-1 text-muted-foreground">{block.title} · {block.date.slice(0, 10)} {block.startTime}-{block.endTime}</p>) : <p className="mt-1 text-muted-foreground">None</p>}</div>; }

function DesktopCalendar({ dates, events, blocks, periods, onEvent, onBlock }: { dates: Record<DayOfWeek, string>; events: EventOccurrence[]; blocks: ScheduleBlock[]; periods: BlockedPeriod[]; onEvent: (value: EventOccurrence) => void; onBlock: (value: ScheduleBlock) => void }) {
  const today = localDate(new Date());
  return <div className="min-w-[1050px]"><div className="sticky top-0 z-30 grid grid-cols-[64px_repeat(7,minmax(138px,1fr))] border-b border-border bg-background"><div /><>{days.map((day) => <div key={day} className={`border-l border-border p-3 text-center ${dates[day] === today ? "bg-primary/10" : ""}`}><strong className="text-sm">{day.slice(0, 3)}</strong><p className="text-xs text-muted-foreground">{dates[day].slice(5)}</p></div>)}</></div><div className="relative grid grid-cols-[64px_repeat(7,minmax(138px,1fr))]" style={{ height: hours.length * 56 }}>{hours.map((hour, index) => <div key={hour} className="absolute left-0 right-0 border-t border-border/70" style={{ top: index * 56 }}><span className="absolute -top-2.5 left-2 bg-background pr-1 text-[10px] text-muted-foreground">{String(hour).padStart(2, "0")}:00</span></div>)}<div />{days.map((day) => <div key={day} className={`relative border-l border-border ${dates[day] === today ? "bg-primary/[0.035]" : ""}`}>{hours.map((hour) => <HourDrop key={hour} id={`${dates[day]}|${hour}`} />)}{periods.filter((period) => period.date.slice(0, 10) === dates[day]).map((period) => <CalendarPeriod key={period.id} period={period} />)}{events.filter((event) => event.date === dates[day]).map((event) => <CalendarEvent key={event.id} event={event} onClick={() => onEvent(event)} />)}{blocks.filter((block) => block.date.slice(0, 10) === dates[day]).map((block) => <CalendarBlock key={block.id} block={block} onClick={() => onBlock(block)} />)}</div>)}</div></div>;
}

function HourDrop({ id }: { id: string }) { const { setNodeRef, isOver } = useDroppable({ id }); return <div ref={setNodeRef} data-testid={`slot-${id}`} className={`h-14 ${isOver ? "bg-primary/15" : ""}`} />; }
function position(start: string, end: string) { const top = (toMinutes(start) - 360) / 60 * 56; const height = Math.max(22, duration(start, end) / 60 * 56); return { top, height }; }
function CalendarEvent({ event, onClick }: { event: EventOccurrence; onClick: () => void }) { const style = position(event.startTime, event.endTime); return <button title={`${event.title} · ${event.startTime}-${event.endTime}`} onClick={onClick} className={`absolute left-1 right-1 z-10 overflow-hidden rounded border p-1 text-left text-[10px] ${sourceStyle.EVENT}`} style={style}><strong className="block truncate">{event.title}</strong><span>{event.startTime}-{event.endTime}</span></button>; }
function CalendarPeriod({ period }: { period: BlockedPeriod }) { const style = period.fullDay ? { top: 0, height: hours.length * 56 } : position(period.startTime!, period.endTime!); return <div title={period.title} className="pointer-events-none absolute inset-x-0 z-[5] border-y border-red-300 bg-red-100/65 p-1 text-[10px] text-red-900 dark:border-red-900 dark:bg-red-950/50 dark:text-red-100" style={style}><BanLabel title={period.title} /></div>; }
function BanLabel({ title }: { title: string }) { return <span className="flex items-center gap-1 font-medium"><AlertTriangle className="size-3" />{title}</span>; }
function CalendarBlock({ block, onClick }: { block: ScheduleBlock; onClick: () => void }) { const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: block.id, disabled: block.locked }); const pos = position(block.startTime, block.endTime); return <button ref={setNodeRef} data-testid={`schedule-block-${block.id}`} {...attributes} {...listeners} title={`${block.title} · ${formatMinutes(duration(block.startTime, block.endTime))} · ${block.sourceType}`} onClick={onClick} className={`absolute left-1 right-1 z-20 overflow-hidden rounded border p-1 text-left text-[10px] shadow-sm ${sourceStyle[block.sourceType]} ${isDragging ? "opacity-60" : ""}`} style={{ ...pos, transform: CSS.Translate.toString(transform) }}><span className="flex items-start justify-between"><strong className="truncate">{block.title}</strong>{block.locked ? <Lock className="size-3" /> : block.completed ? <Check className="size-3" /> : null}</span><span>{block.startTime}-{block.endTime}</span><span className="block uppercase opacity-70">{block.sourceType}</span></button>; }

function MobileDay({ date, events, blocks, periods, onEvent, onBlock }: { date: string; events: EventOccurrence[]; blocks: ScheduleBlock[]; periods: BlockedPeriod[]; onEvent: (value: EventOccurrence) => void; onBlock: (value: ScheduleBlock) => void }) { const items = [...events.map((item) => ({ item, start: item.startTime, type: "event" as const })), ...blocks.map((item) => ({ item, start: item.startTime, type: "block" as const }))].sort((a, b) => a.start.localeCompare(b.start)); return <div className="mt-4 grid gap-3"><p className="text-sm font-medium">{date}</p>{periods.map((period) => <div key={period.id} className="rounded-md border border-red-300 bg-red-50 p-3 text-sm text-red-900"><BanLabel title={`${period.title} · ${period.fullDay ? "All day" : `${period.startTime}-${period.endTime}`}`} /></div>)}{items.map(({ item, type }) => type === "event" ? <button key={item.id} onClick={() => onEvent(item as EventOccurrence)} className={`rounded-md border p-3 text-left text-sm ${sourceStyle.EVENT}`}><strong>{item.title}</strong><p>{item.startTime}-{item.endTime} · Fixed</p></button> : <button key={item.id} onClick={() => onBlock(item as ScheduleBlock)} className={`rounded-md border p-3 text-left text-sm ${sourceStyle[(item as ScheduleBlock).sourceType]}`}><strong>{item.title}</strong><p>{item.startTime}-{item.endTime} · {(item as ScheduleBlock).sourceType}</p></button>)}{!items.length && !periods.length ? <p className="py-10 text-center text-sm text-muted-foreground">No scheduled items</p> : null}</div>; }

function PreviewContent({ preview, weekStart, onCancel, onAccept, accepting }: { preview: SchedulePreview; weekStart: string; onCancel: () => void; onAccept: () => void; accepting: boolean }) { return <div className="grid gap-6"><div className="grid gap-3 sm:grid-cols-3"><Card className="p-4"><p className="text-xs text-muted-foreground">Required</p><p className="mt-1 text-2xl font-semibold">{formatMinutes(preview.summary.requiredMinutes)}</p></Card><Card className="p-4"><p className="text-xs text-muted-foreground">Scheduled</p><p className="mt-1 text-2xl font-semibold text-teal-600">{formatMinutes(preview.summary.scheduledMinutes)}</p></Card><Card className="p-4"><p className="text-xs text-muted-foreground">Unscheduled</p><p className="mt-1 text-2xl font-semibold text-amber-600">{formatMinutes(preview.summary.unscheduledMinutes)}</p></Card></div>{preview.conflicts.map((conflict) => <div key={conflict.eventIds.join(":")} className="rounded-md border border-red-300 bg-red-50 p-3 text-sm text-red-900">{conflict.message}</div>)}{preview.warnings.map((warning) => <div key={`${warning.taskId}:${warning.type}`} className="flex gap-2 rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950"><AlertTriangle className="size-4 shrink-0" />{warning.message}</div>)}<div className="grid gap-3 lg:grid-cols-7">{days.map((day, index) => { const date = shiftDate(weekStart, index); return <section key={day} className="border-t-2 border-border pt-2"><strong className="text-xs">{day.slice(0, 3)}</strong><div className="mt-2 grid gap-2">{preview.proposedBlocks.filter((block) => block.date === date).map((block) => <div key={block.proposalId} className={`rounded border p-2 text-xs ${sourceStyle[block.sourceType]}`}><strong>{block.title}</strong><p>{block.startTime}-{block.endTime}</p></div>)}</div></section>; })}</div><div><h3 className="font-semibold">Task allocation</h3>{preview.summary.allocations.map((item) => <div key={item.taskId} className="flex justify-between border-b border-border py-2 text-sm"><span>{item.title}</span><span>{formatMinutes(item.scheduledMinutes)} / {formatMinutes(item.requiredMinutes)}</span></div>)}</div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onCancel}>Cancel</Button><Button onClick={onAccept} disabled={accepting || preview.conflicts.length > 0}>{accepting ? "Saving..." : "Accept schedule"}</Button></div></div>; }
